// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/cta-endcard.scene.json";
import recipe1 from "./scenes/hero-survey.scene.json";
import recipe2 from "./scenes/pricing-survey.scene.json";
import recipe3 from "./scenes/studio-panel.scene.json";
import recipe4 from "./scenes/tools-plating.scene.json";
export const sceneModules = {
  "src/flute/scenes/cta-endcard.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/cta-endcard.tsx": () => import("./scenes/cta-endcard"),
  "src/flute/scenes/hero-survey.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/hero-survey.tsx": () => import("./scenes/hero-survey"),
  "src/flute/scenes/pricing-survey.scene.json": async () => ({default:recipe2}),
  "src/flute/scenes/pricing-survey.tsx": () => import("./scenes/pricing-survey"),
  "src/flute/scenes/studio-panel.scene.json": async () => ({default:recipe3}),
  "src/flute/scenes/studio-panel.tsx": () => import("./scenes/studio-panel"),
  "src/flute/scenes/tools-plating.scene.json": async () => ({default:recipe4}),
  "src/flute/scenes/tools-plating.tsx": () => import("./scenes/tools-plating"),
};
