// Photo library for marketing pages. Generated from the sourcing notes; every photo is licensed for commercial use.
// Files live in public/images/library/ (see CREDITS.md there for attribution). Unsplash photos without a known
// photographer are credited to "Unsplash contributor"; attribution is not required by the Unsplash License.
import type { ImageKey } from "./types";

export type ImageAsset = { src: string; srcSm: string; width: number; height: number; alt: string; credit: { author: string; source: string; license: string; url: string } };

export const IMAGES: Record<ImageKey, ImageAsset> = {
  "living-modern": {
    src: "/images/library/living-modern.webp",
    srcSm: "/images/library/living-modern-sm.webp",
    width: 1600,
    height: 900,
    alt: "Modern living room with a grey sofa, wood coffee table, arc floor lamp and a long clerestory window",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "living-japandi": {
    src: "/images/library/living-japandi.webp",
    srcSm: "/images/library/living-japandi-sm.webp",
    width: 1600,
    height: 1172,
    alt: "Neutral living room with a cream sofa, boucle armchair, round rattan mirrors and dried pampas grass",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "living-coastal": {
    src: "/images/library/living-coastal.webp",
    srcSm: "/images/library/living-coastal-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Bright living room with beige armchairs, turquoise cushions and large windows overlooking the water",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "living-boho": {
    src: "/images/library/living-boho.webp",
    srcSm: "/images/library/living-boho-sm.webp",
    width: 1600,
    height: 900,
    alt: "Boho living room with woven wall baskets, a red patterned rug, a cream sofa and armchairs, a leather pouf and plants",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "living-classic": {
    src: "/images/library/living-classic.webp",
    srcSm: "/images/library/living-classic-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Formal living room with a coffered ceiling, marble fireplace, built-in shelves and white sofas",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "living-dated": {
    src: "/images/library/living-dated.webp",
    srcSm: "/images/library/living-dated-sm.webp",
    width: 1600,
    height: 1071,
    alt: "Dated condo living room with beige carpet, a cream leather sofa, a painted brick fireplace wall and pleated drapes",
    credit: { author: "cooli_#1", source: "Flickr", license: "CC BY 2.0", url: "https://www.flickr.com/photos/11968082@N03/7207512054" },
  },
  "kitchen-modern": {
    src: "/images/library/kitchen-modern.webp",
    srcSm: "/images/library/kitchen-modern-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Modern kitchen with a white waterfall island, wood cabinetry, four stools and black pendant lights",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "kitchen-farmhouse": {
    src: "/images/library/kitchen-farmhouse.webp",
    srcSm: "/images/library/kitchen-farmhouse-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Farmhouse kitchen with a white apron sink, subway tile, butcher-block counters and black lower cabinets",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "kitchen-dark": {
    src: "/images/library/kitchen-dark.webp",
    srcSm: "/images/library/kitchen-dark-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Kitchen with matte black cabinets, brass hardware, a white countertop and a mosaic tile backsplash",
    credit: { author: "Justin Thomason (West of Main)", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "kitchen-dated": {
    src: "/images/library/kitchen-dated.webp",
    srcSm: "/images/library/kitchen-dated-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Dated kitchen with white 1980s cabinets, laminate countertops, a white range and brown vinyl flooring",
    credit: { author: "Yellowstone National Park", source: "Flickr", license: "Public Domain Mark 1.0", url: "https://www.flickr.com/photos/80223459@N05/50382283233" },
  },
  "bath-spa": {
    src: "/images/library/bath-spa.webp",
    srcSm: "/images/library/bath-spa-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Spa-style bathroom with a freestanding stone bathtub, textured plaster wall, palm plant and pebbles",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "bath-modern": {
    src: "/images/library/bath-modern.webp",
    srcSm: "/images/library/bath-modern-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Modern bathroom with grey stone tiles, a round lit mirror, black vessel sink, wood vanity and freestanding tub",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "bedroom-calm": {
    src: "/images/library/bedroom-calm.webp",
    srcSm: "/images/library/bedroom-calm-sm.webp",
    width: 1600,
    height: 900,
    alt: "Bright bedroom with a grey-blue upholstered bed, white bedding, a woven bench and a potted olive tree",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "bedroom-warm": {
    src: "/images/library/bedroom-warm.webp",
    srcSm: "/images/library/bedroom-warm-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Warm bedroom with a tufted headboard, layered bedding, bedside lamps and an upholstered bench",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "dining-modern": {
    src: "/images/library/dining-modern.webp",
    srcSm: "/images/library/dining-modern-sm.webp",
    width: 1600,
    height: 900,
    alt: "Modern dining room with green velvet chairs, a white table, round mirror, fireplace and plants",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "office-home": {
    src: "/images/library/office-home.webp",
    srcSm: "/images/library/office-home-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Home office with a black accent wall, pale wood desk, laptop, desk lamp and a large window",
    credit: { author: "Justin Thomason (West of Main)", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "kids-room": {
    src: "/images/library/kids-room.webp",
    srcSm: "/images/library/kids-room-sm.webp",
    width: 1600,
    height: 1066,
    alt: "Nursery with a painted star-pattern wall, white crib, grey armchair and arc floor lamp",
    credit: { author: "Paintzen", source: "Flickr", license: "CC BY 2.0", url: "https://www.flickr.com/photos/147489968@N06/29300381464" },
  },
  "empty-room": {
    src: "/images/library/empty-room.webp",
    srcSm: "/images/library/empty-room-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Empty room with light oak floors, a large window, a chandelier and a doorway to a second room",
    credit: { author: "Yellowstone National Park", source: "Flickr", license: "Public Domain Mark 1.0", url: "https://www.flickr.com/photos/80223459@N05/51732820195" },
  },
  "empty-room-2": {
    src: "/images/library/empty-room-2.webp",
    srcSm: "/images/library/empty-room-2-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Empty carpeted room with a sliding glass door, a window onto trees and recessed ceiling lights",
    credit: { author: "Malcolm Lawson", source: "Flickr", license: "CC BY 2.0", url: "https://www.flickr.com/photos/156405257@N06/34802766504" },
  },
  "exterior-modern": {
    src: "/images/library/exterior-modern.webp",
    srcSm: "/images/library/exterior-modern-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Modern two-storey house with white render, a timber-clad block, a garage and a front lawn",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "exterior-farmhouse": {
    src: "/images/library/exterior-farmhouse.webp",
    srcSm: "/images/library/exterior-farmhouse-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Grey shingled farmhouse with a white wraparound porch, dormer windows and a green lawn",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "exterior-brick": {
    src: "/images/library/exterior-brick.webp",
    srcSm: "/images/library/exterior-brick-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Brick and stone suburban house with a double garage, driveway and front lawn",
    credit: { author: "Dillon Kydd", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "exterior-dusk": {
    src: "/images/library/exterior-dusk.webp",
    srcSm: "/images/library/exterior-dusk-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Gabled timber house at dusk with warm interior lights glowing through the windows",
    credit: { author: "Naomi 365 Photography", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "garden-backyard": {
    src: "/images/library/garden-backyard.webp",
    srcSm: "/images/library/garden-backyard-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Backyard lawn with a large gum tree beside a modern house with a covered patio",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "garden-patio": {
    src: "/images/library/garden-patio.webp",
    srcSm: "/images/library/garden-patio-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Timber deck with lounge chairs and a covered outdoor dining area lit at dusk",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "garden-front": {
    src: "/images/library/garden-front.webp",
    srcSm: "/images/library/garden-front-sm.webp",
    width: 1600,
    height: 1200,
    alt: "Stone cottage with a colorful front flower garden and lawn under a blue sky",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "garden-pool": {
    src: "/images/library/garden-pool.webp",
    srcSm: "/images/library/garden-pool-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Backyard swimming pool with a timber deck, sun loungers, stone walls and cypress trees",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "detail-cabinets": {
    src: "/images/library/detail-cabinets.webp",
    srcSm: "/images/library/detail-cabinets-sm.webp",
    width: 1600,
    height: 1067,
    alt: "White shaker kitchen cabinets with copper pulls, hexagon tile backsplash and a marble island",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "detail-countertop": {
    src: "/images/library/detail-countertop.webp",
    srcSm: "/images/library/detail-countertop-sm.webp",
    width: 1600,
    height: 1067,
    alt: "White quartz countertop with subway tile backsplash, cutting boards and a utensil crock",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "detail-flooring": {
    src: "/images/library/detail-flooring.webp",
    srcSm: "/images/library/detail-flooring-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Close view of a herringbone wood floor in a bright room",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "detail-paint": {
    src: "/images/library/detail-paint.webp",
    srcSm: "/images/library/detail-paint-sm.webp",
    width: 1600,
    height: 1117,
    alt: "Paint roller applying light blue paint to a white wall",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "detail-tile": {
    src: "/images/library/detail-tile.webp",
    srcSm: "/images/library/detail-tile-sm.webp",
    width: 1600,
    height: 1066,
    alt: "Close view of white ceramic tiles with a blue symmetrical floral pattern",
    credit: { author: "Nilo Velez", source: "WordPress Photo Directory", license: "CC0 1.0", url: "https://wordpress.org/photos/photo/3386785055/" },
  },
  "sketch-plan": {
    src: "/images/library/sketch-plan.webp",
    srcSm: "/images/library/sketch-plan-sm.webp",
    width: 1600,
    height: 899,
    alt: "Hand-drawn, color-washed floor plan of a small two-bedroom house with furniture and dimensions",
    credit: { author: "Yellowstone National Park", source: "Flickr", license: "Public Domain Mark 1.0", url: "https://www.flickr.com/photos/80223459@N05/49535226928" },
  },
  "smart-home": {
    src: "/images/library/smart-home.webp",
    srcSm: "/images/library/smart-home-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Modern living room with a TV in black media shelving, a pendant light and grey sofas",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "furniture-sofa": {
    src: "/images/library/furniture-sofa.webp",
    srcSm: "/images/library/furniture-sofa-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Green velvet three-seat sofa on a light wood floor against a white wall",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "furniture-chair": {
    src: "/images/library/furniture-chair.webp",
    srcSm: "/images/library/furniture-chair-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Mustard tufted slipper chair on a concrete floor against a grey wall",
    credit: { author: "Unsplash contributor", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
  "decor-shelf": {
    src: "/images/library/decor-shelf.webp",
    srcSm: "/images/library/decor-shelf-sm.webp",
    width: 1600,
    height: 1067,
    alt: "Floating white and oak wall shelves styled with plants, ceramics and a framed print",
    credit: { author: "Michael K. Knop", source: "Unsplash", license: "Unsplash License", url: "https://unsplash.com" },
  },
};
