// Real before/after pairs produced by Roomwright itself. Generated by
// scripts/generate-showcase.mjs once an AI provider is connected; never hand-made.
// The home page only shows the showcase section when this list has entries.

import type { ToolId } from "@/lib/tools";

export type ShowcaseItem = {
  id: string;
  title: string;
  tool: ToolId;
  detail: string;
  before: string;
  after: string;
  width: number;
  height: number;
};

export const SHOWCASE: ShowcaseItem[] = [];
